version: '3.2'

services:
  posting:
    build:
      context: .
      dockerfile: Dockerfile
    image: instagrambot:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
      - type: bind
        source: ../log
        target: /log
      - type: bind
        source: ../data
        target: /data
      - type: bind
        source: ../configs
        target: /configs
    working_dir: /workdir
    command: python posting.py
